### ISSUE TITLE
Ignore any local packages in .stack2cabal when considering tested-with.

### ISSUE THREAD

**Issue by philderbeast** [haskell-CI/haskell-ci#156]
Can we please ignore any local packages in `.stack2cabal` or any dot-prefixed folder when considering `tested-with`? Also can we please use the `tested-with` in `cabal.project` if that exists?

To reproduce, working off `flare-timing` at revision [68e62b](https://github.com/BlockScope/flare-timing/commits/68e62b236ca4e7207e559eeb5aec7bb69f44cc6e);

If I use [stack2cabal](https://github.com/brunjlar/stack2cabal) this enables me to depend on packages from github that are then cloned locally to `.stack2cabal`.

```
> stack install stack2cabal
> stack exec stack2cabal .
creating cabal config for project folder '.'
```

Here's the generated `cabal.project` file. I've added `tested-with` and edited the packages to include the same list that's in `stack.yaml` and removed the version constraints.

```
tested-with: GHC == 8.2.2
packages:
    .stack2cabal/fgl
    , .stack2cabal/uom-plugin/uom-plugin
    , .stack2cabal/hcoord/hcoord
    , .stack2cabal/hcoord/hcoord-utm
    , build
    , aeson-via-sci
    , aeson-via-uom
    , cmd
    , comp
    , earth
    , fsdb
    , gap
    , igc
    , kml
    , latlng
    , lookup
    , mask
    , route
    , scribe
    , siggy-chardust
    , span
    , task
    , tasty-compare
    , track
    , units
    , zone
```

```
- location:
    git: https://github.com/blockscope/hcoord.git
    commit: efee5918967a4b5309924bb6ac62c2daa56983a1
  subdirs:
  - hcoord
  - hcoord-utm
  extra-dep: true
- location:
    git: https://github.com/haskell/fgl.git
    commit: e29503775e474b7a7cd8951b6bebcf1529b888b5
  extra-dep: true
- location:
    git: https://github.com/blockscope/uom-plugin.git
    commit: 107fdd7bcdb22e2afef5d868e7b902f49690dd30
  subdirs:
  - uom-plugin
  extra-dep: true
- location:
    git: https://github.com/brunjlar/stack2cabal
    commit: a8a4cdcacd697cee648af93856735f15de5987a6
  extra-dep: true
- location:
    git: https://github.com/haskell-CI/haskell-ci
    commit: 105005cde6bde903e477e5b9724d02bdea06bae4
  extra-dep: true
```

With the above snippet in `stack.yaml`, I can also use `stack install` to install `haskell-ci` and use it to try to generate the travis setup but it fails because a cloned and now local git dependency does not have `tested-with`.

```
> stack install haskell-ci
> stack exec make-travis-yml -- cabal.project
*ERROR* empty or missing top-level 'tested-with:' definition in .stack2cabal/hcoord/hcoord/hcoord.cabal file; example definition:

tested-with: GHC==8.4.2, GHC==8.2.2, GHC==8.0.2, GHC==7.10.3, GHC==7.8.4, GHC==7.6.3, GHC==7.4.2, GHC==7.2.2, GHC==7.0.4
```
