### ISSUE TITLE
Support Travis’s deploy feature

### ISSUE THREAD

**Issue by nomeata** [haskell-CI/haskell-ci#36]
With the auto-generated `.travis.yml`, I guess all possible features  of travis now need to be supported by the the script...

Anyways, it seems that Travis supports pushing releases to hackage upon an successful build:
http://docs.travis-ci.com/user/deployment/hackage/

I’m currently experimenting with 

```
deploy:
  provider: hackage
  on:
    condition: "$GHCVER = 7.8.4"
    tags: true
  username: "JoachimBreitner"
  password:
    secure: "...."
```

It would be nice if there was a good way to get such a snippet into the auto-generated file.
