### ISSUE TITLE
source-repository-packages are printed twice with copy-fields=all

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#390]
To reproduce this issue, you will need the following two files:

* `cabal.project`:

  ```
  packages: .
  
  source-repository-package
      type:     git
      location: https://github.com/haskell-CI/haskell-ci
      tag:      eb107ae2a826d28f4ec91ba9af5bb6080372deea
  ```
* `example.cabal`:

  ```
  cabal-version:       3.0
  name:                example
  version:             0.1.0.0
  build-type:          Simple
  tested-with:         GHC==8.10.1
  ```

Now run the following command:

```
$ haskell-ci --version
0.10
$ haskell-ci cabal.project --copy-fields=all --output=.travis.yml
*INFO* Generating Travis-CI config for testing for GHC versions: 8.10.1
```

You will end up with the following `.travis.yml` file:

<details>

```yaml
# This Travis job script has been generated by a script via
#
#   haskell-ci 'cabal.project' '--copy-fields=all' '--output=.travis.yml'
#
# To regenerate the script (for example after adjusting tested-with) run
#
#   haskell-ci regenerate
#
# For more information, see https://github.com/haskell-CI/haskell-ci
#
# version: 0.10
#
version: ~> 1.0
language: c
os: linux
dist: xenial
git:
  # whether to recursively clone submodules
  submodules: false
cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.hlint
before_cache:
  - rm -fv $CABALHOME/packages/hackage.haskell.org/build-reports.log
  # remove files that are regenerated by 'cabal update'
  - rm -fv $CABALHOME/packages/hackage.haskell.org/00-index.*
  - rm -fv $CABALHOME/packages/hackage.haskell.org/*.json
  - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.cache
  - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar
  - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar.idx
  - rm -rfv $CABALHOME/packages/head.hackage
jobs:
  include:
    - compiler: ghc-8.10.1
      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.10.1","cabal-install-3.2"]}}
      os: linux
before_install:
  - HC=$(echo "/opt/$CC/bin/ghc" | sed 's/-/\//')
  - WITHCOMPILER="-w $HC"
  - HADDOCK=$(echo "/opt/$CC/bin/haddock" | sed 's/-/\//')
  - HCPKG="$HC-pkg"
  - unset CC
  - CABAL=/opt/ghc/bin/cabal
  - CABALHOME=$HOME/.cabal
  - export PATH="$CABALHOME/bin:$PATH"
  - TOP=$(pwd)
  - "HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\\d+)\\.(\\d+)\\.(\\d+)(\\.(\\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')"
  - echo $HCNUMVER
  - CABAL="$CABAL -vnormal+nowrap"
  - set -o pipefail
  - TEST=--enable-tests
  - BENCH=--enable-benchmarks
  - HEADHACKAGE=false
  - rm -f $CABALHOME/config
  - |
    echo "verbose: normal +nowrap +markoutput"          >> $CABALHOME/config
    echo "remote-build-reporting: anonymous"            >> $CABALHOME/config
    echo "write-ghc-environment-files: always"          >> $CABALHOME/config
    echo "remote-repo-cache: $CABALHOME/packages"       >> $CABALHOME/config
    echo "logs-dir:          $CABALHOME/logs"           >> $CABALHOME/config
    echo "world-file:        $CABALHOME/world"          >> $CABALHOME/config
    echo "extra-prog-path:   $CABALHOME/bin"            >> $CABALHOME/config
    echo "symlink-bindir:    $CABALHOME/bin"            >> $CABALHOME/config
    echo "installdir:        $CABALHOME/bin"            >> $CABALHOME/config
    echo "build-summary:     $CABALHOME/logs/build.log" >> $CABALHOME/config
    echo "store-dir:         $CABALHOME/store"          >> $CABALHOME/config
    echo "install-dirs user"                            >> $CABALHOME/config
    echo "  prefix: $CABALHOME"                         >> $CABALHOME/config
    echo "repository hackage.haskell.org"               >> $CABALHOME/config
    echo "  url: http://hackage.haskell.org/"           >> $CABALHOME/config
install:
  - ${CABAL} --version
  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - |
    echo "program-default-options"                >> $CABALHOME/config
    echo "  ghc-options: $GHCJOBS +RTS -M6G -RTS" >> $CABALHOME/config
  - cat $CABALHOME/config
  - rm -fv cabal.project cabal.project.local cabal.project.freeze
  - travis_retry ${CABAL} v2-update -v
  # Generate cabal.project
  - rm -rf cabal.project cabal.project.local cabal.project.freeze
  - touch cabal.project
  - |
    echo "packages: ." >> cabal.project
  - echo 'package example' >> cabal.project
  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
  - |
    echo "source-repository-package"                            >> cabal.project
    echo "  type:     git"                                      >> cabal.project
    echo "  location: https://github.com/haskell-CI/haskell-ci" >> cabal.project
    echo "  tag:      eb107ae2a826d28f4ec91ba9af5bb6080372deea" >> cabal.project
    echo ""                                                     >> cabal.project
    echo "source-repository-package"                            >> cabal.project
    echo "  type:     git"                                      >> cabal.project
    echo "  location: https://github.com/haskell-CI/haskell-ci" >> cabal.project
    echo "  tag:      eb107ae2a826d28f4ec91ba9af5bb6080372deea" >> cabal.project
  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(example)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
  - cat cabal.project || true
  - cat cabal.project.local || true
  - if [ -f "./configure.ac" ]; then (cd "." && autoreconf -i); fi
  - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH}
  - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
  - rm  cabal.project.freeze
  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} --dep -j2 all
  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks --dep -j2 all
script:
  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
  # Packaging...
  - ${CABAL} v2-sdist all
  # Unpacking...
  - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
  - cd ${DISTDIR} || false
  - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
  - find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
  - PKGDIR_example="$(find . -maxdepth 1 -type d -regex '.*/example-[0-9.]*')"
  # Generate cabal.project
  - rm -rf cabal.project cabal.project.local cabal.project.freeze
  - touch cabal.project
  - |
    echo "packages: ${PKGDIR_example}" >> cabal.project
  - echo 'package example' >> cabal.project
  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
  - |
    echo "source-repository-package"                            >> cabal.project
    echo "  type:     git"                                      >> cabal.project
    echo "  location: https://github.com/haskell-CI/haskell-ci" >> cabal.project
    echo "  tag:      eb107ae2a826d28f4ec91ba9af5bb6080372deea" >> cabal.project
    echo ""                                                     >> cabal.project
    echo "source-repository-package"                            >> cabal.project
    echo "  type:     git"                                      >> cabal.project
    echo "  location: https://github.com/haskell-CI/haskell-ci" >> cabal.project
    echo "  tag:      eb107ae2a826d28f4ec91ba9af5bb6080372deea" >> cabal.project
  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(example)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
  - cat cabal.project || true
  - cat cabal.project.local || true
  # Building...
  # this builds all libraries and executables (without tests/benchmarks)
  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all
  # Building with tests and benchmarks...
  # build & run tests, build benchmarks
  - ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} all
  # cabal check...
  - (cd ${PKGDIR_example} && ${CABAL} -vnormal check)
  # Building without installed constraints for packages in global-db...
  - rm -f cabal.project.local
  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all

# REGENDATA ("0.10",["cabal.project","--copy-fields=all","--output=.travis.yml"])
# EOF
```
</details>

Notice the following at around lines 90-98 (and 126-134):

```yaml
    echo "source-repository-package"                            >> cabal.project
    echo "  type:     git"                                      >> cabal.project
    echo "  location: https://github.com/haskell-CI/haskell-ci" >> cabal.project
    echo "  tag:      eb107ae2a826d28f4ec91ba9af5bb6080372deea" >> cabal.project
    echo ""                                                     >> cabal.project
    echo "source-repository-package"                            >> cabal.project
    echo "  type:     git"                                      >> cabal.project
    echo "  location: https://github.com/haskell-CI/haskell-ci" >> cabal.project
    echo "  tag:      eb107ae2a826d28f4ec91ba9af5bb6080372deea" >> cabal.project
```

The `source-repository-package` ends up being printed twice. This appears to be harmless, as `cabal` can cope with duplicate `source-repository-package`s without failing, but it is redundant nevertheless.

This bug does not occur if `--copy-fields=some` is used instead of `--copy-fields=all`.
