### ISSUE TITLE
is there a need to evolve to a new CI target?

### ISSUE THREAD

**Issue by cartazio** [haskell-CI/haskell-ci#411]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing has some nontrivial resource limits added for OSS usage
(i'm also seeing some really long build queing waits with travis atm)

i'm poking at using https://github.com/actions/setup-haskell 

heres my example based on their readme https://github.com/cartazio/ralist/actions/runs/362414677 (not sure if that link is public)

```yaml
on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:  ['7.10.3','8.0.2','8.2.2','8.6.5', '8.8.3','8.10.2','latest'] # ['7.0.4','7.2.2','7.4.2','7.6.3','7.8.4',
        cabal: ['3.2.0.0'] # ,'latest'

        os: [ubuntu-latest] #, macOS-latest, windows-latest]
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8.3
            cabal: 2.4.1.0

        include:
      # for the matrix leg matching the os and version
          - os: windows-latest
            ghc: latest
            cabal: latest
          - os: macOS-latest
            ghc: latest
            cabal: latest
          - os: ubuntu-latest
            ghc: latest
            cabal: latest
    name: Haskell GHC ${{ matrix.ghc }} and cabal ${{matrix.cabal}} on ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.3 # the .3 is a bug fix?
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal test
```
