### ISSUE TITLE
GHA doesn't support [skip ci] out of the box

### ISSUE THREAD

**Issue by sgraf812** [haskell-CI/haskell-ci#454]
See https://github.community/t/github-actions-does-not-respect-skip-ci/17325. But as the thread also reveals, there are ways round it. For example

```yaml
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
```

Or depending on https://github.com/marketplace/actions/ci-skip-action.
