### ISSUE TITLE
GHA does not implement --ghc-head job

### ISSUE THREAD

**Issue by frasertweedale** [haskell-CI/haskell-ci#460]
(At commit a4ea1ed56c7047619f755aeef8a39e35798ddc8e.)

The `github` target does not implement `--ghc-head` jobs.  Example:

```yaml
# This GitHub workflow config has been generated by a script via
#
#   haskell-ci '--hlint' '--haddock' '--ghc-head' 'github' 'purebred-email.cabal'
#
# To regenerate the script (for example after adjusting tested-with) run
#
#   haskell-ci regenerate
#
# For more information, see https://github.com/haskell-CI/haskell-ci
#
# version: 0.11.20210101
#
# REGENDATA ("0.11.20210101",["--hlint","--haddock","--ghc-head","github","purebred-email.cabal"])
#
name: Haskell-CI
on:
  - push
  - pull_request
jobs:
  linux:
    name: Haskell-CI Linux - GHC ${{ matrix.ghc }}
    runs-on: ubuntu-18.04
    container:
      image: buildpack-deps:bionic
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        include:
          - ghc: 8.10.3
            allow-failure: false
          - ghc: 8.8.4
            allow-failure: false
          - ghc: 8.6.5
            allow-failure: false
          - ghc: 8.4.4
            allow-failure: false
      fail-fast: false
    steps:
      ...
```

Expected result: a ghc-head job added to the matrix, with `allow-failure: true` (by default).
