### ISSUE TITLE
Download of GHC fails on Travis

### ISSUE THREAD

**Issue by LeventErkok** [haskell-CI/haskell-ci#545]
I'm not exactly sure if `haskell-ci` is to blame here, but my travis builds recently started failing. The signature is:

```
Adding APT Sources
1650.56s$ curl -sSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286" | sudo -E apt-key add -
166curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
167More details here: http://curl.haxx.se/docs/sslcerts.html
```

I'm pretty sure this is not directly haskell-ci, but perhaps what it "assumes" of the state of the internet?

I'm happy to report elsewhere if you can point me where to. The offending line in the `.travis.yml` file generated by `haskell-ci` seems to be:

```
jobs:
  include:
    - compiler: ghc-9.0.1
      addons: {"apt":{"packages":["ghc-9.0.1","cabal-install-3.4"],"sources":[{"key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286","sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main"}]}}
      os: linux
```
